# Use a modern Node.js version
FROM node:22-slim

# Create app directory
RUN mkdir -p /app

# Set working directory
WORKDIR /app

# Copy only package.json & package-lock.json to use cache
COPY package*.json ./

# Install dependencies before copying other files
RUN npm install --verbose

# Now copy the rest of the files
COPY . .

# Show contents for debugging (Remove after testing)
RUN ls -l /app

# Expose the port
EXPOSE 4000

# Start the application
CMD ["node", "app.js"]
